### ISSUE TITLE
Learner certificates don't include workshop name, won't export in some environments

### ISSUE THREAD

**Issue by brianmatthewthomas** [carpentries/learner-certificates#4]
I was trying to export a bunch of learner certificates and noticed a couple of things that seemed off: (1) There was no workshop lesson name so if an attendee needed credit for individual lessons, then the certificate wouldn't suffice; and (2) the export process was not working on my Linux Ubuntu virtual machine no matter how hard I tried.

So...I created a certificate svg file that included a workshop name option, and then a pandas-based alternative export script that operates on a Q/A input basis. I tried to do a pull request to submit the additions but something went wrong and I am getting a no permissions error. Can someone help me with submitting that additional options for consideration?

**Comment by fmichonneau** [comment]
Hi Brian,

Thanks for bringing this up.

I'm not sure what could have gone wrong in your virtual machine but I use Ubuntu and can generate the certificates.

```shell
# install the python libraries needed
python -m pip install -r requirements.txt
# generate the svg version of the certificate
jinja2 swc-attendance.svg -D name="test test" -D date="2021-08-15" -D instructor="test instructor" > test.svg
# convert svg to pdf
svg2pdf test.svg test.pdf
```

A pull request that adds the name of the workshop would be welcome!

Looking at your fork: https://github.com/brianmatthewthomas/learner-certificates, I don't see any new branches or commit that would indicate that you have pushed the changes to the repository. could you please double-check that it's the case and I'd then happily bring these changes here!

**Comment by maneesha** [comment]
Closing as stale.
